# -*- coding: utf-8 -*-
"""NLP Mini Project: Analyzing Classic Literature

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCslFIDel2y5f40djSrpPxgPG8iDWPef
"""

import nltk
nltk.download('gutenberg')
nltk.corpus.gutenberg.fileids()

import nltk
nltk.data.path.append("/path/to/nltk_data")  # Replace with the actual path
nltk.download('punkt')

#Gutenberg Corpus
emma=nltk.corpus.gutenberg.words('austen-emma.txt')
len(emma)
emma=nltk.Text(nltk.corpus.gutenberg.words('austen-emma.txt'))
emma.concordance("surprize")

from nltk.corpus import gutenberg
gutenberg.fileids()
emma=gutenberg.words('austen-emma.txt')

for fileid in gutenberg.fileids():
  num_chars = len(gutenberg.raw(fileid))
  num_words = len(gutenberg.words(fileid))
  num_sents = len(gutenberg.sents(fileid))
num_vocab = len(set(w.lower() for w in gutenberg.words(fileid)))

print(round(num_chars/num_words), round(num_words/num_sents), round(num_words/num_vocab), fileid)

