# -*- coding: utf-8 -*-
"""Verb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4SM25cFMn3ocJdBy7-P_t9DYEeXGpqY
"""

def marathi_verb_pluralisation(verb, gender, number):
    # Define the verb conjugation rules
    verb_conjugation = {
        ('masculine', 'singular'): verb + 'āt',
        ('masculine', 'plural'): verb + 'at',
        ('feminine', 'singular'): verb + 'ti',
        ('feminine', 'plural'): verb + 'ti',
        ('neuter', 'singular'): verb + 't',
        ('neuter', 'plural'): verb + 'at'
    }

    # Get the verb form based on the subject's gender and number
    verb_form = verb_conjugation[(gender, number)]

    return verb_form

# Test the function
print(marathi_verb_pluralisation('kha', 'masculine', 'singular'))
print(marathi_verb_pluralisation('ja', 'masculine', 'plural'))
print(marathi_verb_pluralisation('bol', 'feminine', 'singular'))
print(marathi_verb_pluralisation('chal', 'feminine', 'plural'))
print(marathi_verb_pluralisation('mar', 'neuter', 'singular'))
print(marathi_verb_pluralisation('radd', 'neuter', 'plural'))
print(marathi_verb_pluralisation('zop', 'feminine', 'singular'))
print(marathi_verb_pluralisation('bhet', 'feminine', 'plural'))
print(marathi_verb_pluralisation('pi', 'neuter', 'singular'))
print(marathi_verb_pluralisation('bagh', 'neuter', 'plural'))

def marathi_verb_tense(verb, tense):
    # Define the verb conjugation rules for different tenses
    verb_conjugation = {
        'present': {
            'first_singular': verb + 'to',
            'second_singular': verb + 'tos',
            'third_singular': verb + 'to',
            'first_plural': verb + 'to',
            'second_plural': verb + 'ta',
            'third_plural': verb + 'tat'
        },
        'past': {
            'first_singular': verb + 'lo',
            'second_singular': verb + 'las',
            'third_singular': verb + 'la',
            'first_plural': verb + 'lo',
            'second_plural': verb + 'lat',
            'third_plural': verb + 'le'
        },
        'future': {
            'first_singular': verb + 'n',
            'second_singular': verb + 'shil',
            'third_singular': verb + 'l',
            'first_plural': verb + 'lu',
            'second_plural': verb + 'ɻal',
            'third_plural': verb + 'til'
        },
        'imperative': {
            'second_singular': verb + 'e',
            'second_plural': verb + 'o'
        }
    }

    # Get the verb form based on the tense
    if tense in verb_conjugation:
        verb_form = verb_conjugation[tense]
    elif tense == 'third_singular':
        verb_form = verb_conjugation['past']['third_singular']
    elif tense == 'first_plural':
        verb_form = verb_conjugation['present']['first_plural']
    elif tense == 'second_plural':
        verb_form = verb_conjugation['present']['second_plural']
    elif tense == 'third_plural':
        verb_form = verb_conjugation['present']['third_plural']
    else:
        verb_form = verb_conjugation['past']['third_plural']

    return verb_form

# Test the function
print(marathi_verb_tense('kha', 'present'))
print(marathi_verb_tense('khel','past'))
print(marathi_verb_tense('bol', 'future'))
print(marathi_verb_tense('mar', 'third_singular'))
print(marathi_verb_tense('radd', ''))
print(marathi_verb_tense('zop', 'imperative'))
print(marathi_verb_tense('bhet', 'present'))
print(marathi_verb_tense('pi','past'))
print(marathi_verb_tense('bhet', 'future'))
print(marathi_verb_tense('sang', 'future'))